export type QuoteEntry = {
  id: string;
  characterName: string;
  seriesName: string;
  shortQuote: string;
  line: string;
  accentColor: string;
  emblem: string;
  imageUrl: string;
  sourceUrl: string;
};

export const quotes: QuoteEntry[] = [
  {
    id: "luffy",
    characterName: "Monkey D. Luffy",
    seriesName: "One Piece",
    shortQuote: "I'm gonna be King of the Pirates!",
    line: "I don't want to rule anyone. I want to be free. I'll sail wherever I want, protect the people who matter to me, and keep moving forward no matter how impossible the road becomes. If someone stands between me and my dream, I'll overcome them. No matter how many times I fall, I'll get back up. One day, I'll reach the end of the sea and become the freest man alive.",
    accentColor: "#e8402c", emblem: "☀",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png",
    sourceUrl: "https://anilist.co/character/40",
  },
  {
    id: "itachi",
    characterName: "Itachi Uchiha",
    seriesName: "Naruto",
    shortQuote: "People live their lives bound by what they accept as correct.",
    line: "People see the world through their own understanding and call that understanding the truth. A shinobi may be forced to make choices that others could never understand. Sometimes protecting the people you love means carrying a burden alone. True strength is not simply defeating an enemy. It is accepting the consequences of your choices and continuing forward without needing the world to understand you.",
    accentColor: "#b82838", emblem: "月",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png",
    sourceUrl: "https://anilist.co/character/14",
  },
  {
    id: "madara",
    characterName: "Madara Uchiha",
    seriesName: "Naruto",
    shortQuote: "Wake up to reality.",
    line: "Wake up to reality. The world is not shaped by dreams of peace. People speak about peace while creating the conditions for another war. Every victory creates resentment, every loss creates hatred, and every generation inherits the wounds of the one before it. Humanity continues walking through the same cycle because it refuses to face what reality truly is. As long as people remain trapped within that cycle, peace will remain an illusion.",
    accentColor: "#9f2336", emblem: "炎",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b53901-HnRKSoHMG5Vg.png",
    sourceUrl: "https://anilist.co/character/53901",
  },
  {
    id: "zoro",
    characterName: "Roronoa Zoro",
    seriesName: "One Piece",
    shortQuote: "Nothing happened.",
    line: "I made a promise, and I will keep it. I don't care how many enemies stand in front of me or how much pain I have to endure. My captain has his dream, and I have mine. If I cannot become the world's greatest swordsman, then I have no right to stand beside him. I'll endure everything that comes my way and keep moving forward until I reach the top.",
    accentColor: "#65b886", emblem: "⚔",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png",
    sourceUrl: "https://anilist.co/character/62",
  },
  {
    id: "aizen",
    characterName: "Sosuke Aizen",
    seriesName: "Bleach",
    shortQuote: "Admiration is the furthest thing from understanding.",
    line: "People naturally look upward when they cannot understand something. They call it greatness because they cannot comprehend what stands before them. But admiration creates distance, and distance creates misunderstanding. Those who are truly powerful do not need permission to stand above others. They simply move forward while everyone else tries to understand what they have already surpassed.",
    accentColor: "#9c7a55", emblem: "鏡",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b1086-qR9218BjZTC0.png",
    sourceUrl: "https://anilist.co/character/1086",
  },
  {
    id: "obito",
    characterName: "Obito Uchiha",
    seriesName: "Naruto",
    shortQuote: "In the ninja world, those who break the rules are scum.",
    line: "The world teaches people to follow rules, yet it creates situations where following those rules can cost innocent lives. I once believed that bonds and hope could overcome anything. Then reality showed me how easily everything can be taken away. When the world destroys the future you believed in, it becomes tempting to create a different reality where none of that pain ever existed.",
    accentColor: "#d06842", emblem: "眼",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b3149-j6cl8A9yup51.png",
    sourceUrl: "https://anilist.co/character/3149",
  },
  {
    id: "gojo",
    characterName: "Satoru Gojo",
    seriesName: "Jujutsu Kaisen",
    shortQuote: "Throughout heaven and earth, I alone am the honored one.",
    line: "Being the strongest doesn't mean everything becomes easy. Strength can separate you from everyone around you. But I don't want the next generation to inherit the same broken world. If I'm strong enough to change things, then I'll use that strength to create a future where others can grow beyond what came before them. The old system doesn't have to decide what comes next.",
    accentColor: "#57cce8", emblem: "∞",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png",
    sourceUrl: "https://anilist.co/character/127691",
  },
  {
    id: "sukuna",
    characterName: "Ryomen Sukuna",
    seriesName: "Jujutsu Kaisen",
    shortQuote: "Know your place, fool.",
    line: "You mistake confidence for arrogance because you have never stood before something truly beyond your understanding. Power does not ask for permission. It does not apologize for existing. Those who are strong survive, and those who cannot withstand that strength are crushed beneath it. Struggle if you wish. Resist if you can. In the end, reality will remind you exactly where you stand.",
    accentColor: "#d43f55", emblem: "呪",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b133701-rCQuDpHr3UZL.png",
    sourceUrl: "https://anilist.co/character/133701",
  },
  {
    id: "jinwoo",
    characterName: "Sung Jinwoo",
    seriesName: "Solo Leveling",
    shortQuote: "Arise.",
    line: "I know what it means to be weak. I know what it feels like to be the person everyone expects to fail. But weakness does not have to be permanent. Every battle made me stronger. Every defeat became another reason to rise. I don't need someone else to protect me anymore. I will become strong enough to protect everything I refuse to lose.",
    accentColor: "#9e7cff", emblem: "影",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b129928-BCEjVaP0AQSw.png",
    sourceUrl: "https://anilist.co/character/129928",
  },
  {
    id: "levi",
    characterName: "Levi Ackerman",
    seriesName: "Attack on Titan",
    shortQuote: "The only truth is that we don't know what will happen.",
    line: "There is no way to know which decision is correct before you make it. You can gather information, calculate the risks, and still lose everything. That's the reality of this world. So choose what you believe you can live with. Trust the people beside you, accept the consequences, and keep moving forward even when the answer isn't clear.",
    accentColor: "#7aa89a", emblem: "翼",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b45627-CR68RyZmddGG.png",
    sourceUrl: "https://anilist.co/character/45627",
  },
  {
    id: "light",
    characterName: "Light Yagami",
    seriesName: "Death Note",
    shortQuote: "I will become the god of this new world.",
    line: "The world is filled with people who create suffering and escape without consequence. If the existing system cannot create the world I believe humanity deserves, then I will create another one. I will decide what justice means, reshape society according to my vision, and become the symbol of a new world. The question is no longer whether change will happen, but who will control it.",
    accentColor: "#bc9b4e", emblem: "K",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png",
    sourceUrl: "https://anilist.co/character/80",
  },
  {
    id: "ryuk",
    characterName: "Ryuk",
    seriesName: "Death Note",
    shortQuote: "Humans are interesting.",
    line: "Humans are strange creatures. They fear death, yet they constantly move toward danger. They create rules and then search for ways around them. They claim to value life while destroying each other over ideas and ambition. That's what makes watching them so entertaining. You never really know what a human will do when they believe they have nothing left to lose.",
    accentColor: "#7684a2", emblem: "D",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b75-IkEpzO21LgFy.jpg",
    sourceUrl: "https://anilist.co/character/75",
  },
  {
    id: "johan",
    characterName: "Johan Liebert",
    seriesName: "Monster",
    shortQuote: "The only thing all humans are equal in is death.",
    line: "People spend their lives believing that they are different from everyone else. They build identities, dreams, relationships, and reasons to continue living. Yet beneath all those differences is the same fragile existence. Remove the things people use to define themselves, and you discover how quickly certainty disappears. Perhaps the most frightening thing about humanity is how easily meaning can be created and destroyed.",
    accentColor: "#c2aa7e", emblem: "M",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b719-y984mDWyGf5n.jpg",
    sourceUrl: "https://anilist.co/character/719",
  },
  {
    id: "griffith",
    characterName: "Griffith",
    seriesName: "Berserk",
    shortQuote: "A dream is something you do for yourself.",
    line: "A dream is not something you borrow from someone else. It is the destination you choose for yourself, even when reaching it demands sacrifices. People may walk beside you, support you, or even give everything for your dream, but the dream itself remains yours. To abandon it completely would mean abandoning the person you chose to become.",
    accentColor: "#b7bfd8", emblem: "鷹",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b424-Jfrsf8I7zBps.png",
    sourceUrl: "https://anilist.co/character/424",
  },
  {
    id: "yhwach",
    characterName: "Yhwach",
    seriesName: "Bleach",
    shortQuote: "Fear is necessary for evolution.",
    line: "People fear what they cannot understand and fear what they cannot control. They believe the future is something they must wait for, but the future can be shaped by those powerful enough to seize it. Fear reveals weakness, and weakness creates the desire to evolve beyond one's limits. Those who can see what lies ahead are not bound by the uncertainty that controls everyone else.",
    accentColor: "#8b75a8", emblem: "Y",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b68537-1bRB5OdseCp0.jpg",
    sourceUrl: "https://anilist.co/character/68537",
  },
  {
    id: "shanks",
    characterName: "Shanks",
    seriesName: "One Piece",
    shortQuote: "You can pour drinks on me, throw food at me, even spit on me.",
    line: "There are things worth fighting for and things that are not. Insults, humiliation, and foolish behavior are not enough to make me draw my sword. But when someone threatens the people I care about or crosses a line that cannot be ignored, everything changes. True strength isn't proving that you can fight. It is knowing when a fight is actually worth having.",
    accentColor: "#c7443e", emblem: "海",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b727-wUJx7M1z5xON.png",
    sourceUrl: "https://anilist.co/character/727",
  },
  {
    id: "whitebeard",
    characterName: "Edward Newgate",
    seriesName: "One Piece",
    shortQuote: "One Piece does exist!",
    line: "A man's life is measured by more than the number of years he survives. It is measured by the people he protects, the bonds he creates, and the legacy he leaves behind. Treasure isn't always something you can hold in your hands. Sometimes it is the family you found along the way and the dream that continues after you are gone.",
    accentColor: "#e2c153", emblem: "W",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b2751-NnzW0N2vCTjX.jpg",
    sourceUrl: "https://anilist.co/character/2751",
  },
  {
    id: "ace",
    characterName: "Portgas D. Ace",
    seriesName: "One Piece",
    shortQuote: "Thank you for loving me.",
    line: "For a long time, I wondered whether I had any reason to exist. I questioned whether someone like me deserved to be alive. But then I met people who accepted me, stood beside me, and called me family. Maybe the greatest proof that my life had meaning was not what I accomplished, but the people who made me feel that I was worth loving.",
    accentColor: "#ee7138", emblem: "火",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b2072-Lc6jEdsueJUK.jpg",
    sourceUrl: "https://anilist.co/character/2072",
  },
  {
    id: "kakashi",
    characterName: "Kakashi Hatake",
    seriesName: "Naruto",
    shortQuote: "Those who abandon their friends are worse than scum.",
    line: "Rules are important, but they cannot be more important than the people standing beside you. A mission can be completed and a mistake can be corrected, but a person who is lost cannot simply be brought back. Protecting your comrades means accepting responsibility when things go wrong and refusing to abandon them when the situation becomes difficult.",
    accentColor: "#8a9eff", emblem: "雷",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png",
    sourceUrl: "https://anilist.co/character/85",
  },
  {
    id: "pain",
    characterName: "Pain",
    seriesName: "Naruto",
    shortQuote: "Those who do not understand true pain can never understand peace.",
    line: "People ask for peace because they fear suffering, yet many have never experienced enough pain to understand what it truly means. When someone loses everything, their understanding of the world changes. Hatred creates more hatred, and revenge creates another reason for someone else to seek revenge. Until people understand the consequences of suffering, they will continue repeating the same cycle.",
    accentColor: "#b85c46", emblem: "痛",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b3180-ITMGBLWNBOgV.png",
    sourceUrl: "https://anilist.co/character/3180",
  },
  {
    id: "minato",
    characterName: "Minato Namikaze",
    seriesName: "Naruto",
    shortQuote: "A true hero is someone who never gives up.",
    line: "A shinobi's greatest strength isn't simply how powerful their techniques are. It is the determination to protect what matters even when the outcome seems impossible. There will always be moments when fear tells you to stop. But if you continue moving forward and trust the people who believe in you, even the impossible can become a path toward tomorrow.",
    accentColor: "#e6c343", emblem: "閃",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b2535-Xq9WKNPJQEt3.png",
    sourceUrl: "https://anilist.co/character/2535",
  },
  {
    id: "sasuke",
    characterName: "Sasuke Uchiha",
    seriesName: "Naruto",
    shortQuote: "My only goal is in the darkness.",
    line: "I chose my path a long time ago. Everything I do is connected to the goal I have carried since the beginning. I know that the road ahead will isolate me from others, but I cannot pretend that the past does not exist. Until I settle what remains unresolved inside me, I cannot simply turn around and choose an easier path.",
    accentColor: "#7069b8", emblem: "鷹",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png",
    sourceUrl: "https://anilist.co/character/13",
  },
  {
    id: "naruto",
    characterName: "Naruto Uzumaki",
    seriesName: "Naruto",
    shortQuote: "I never go back on my word. That is my ninja way.",
    line: "I know what it feels like when nobody believes in you. I know what it means to be alone and ignored. That's why I refuse to abandon someone just because their path became difficult. I made a promise to myself that I would never run away from my word. No matter how hard things become, I'll keep moving until I find another way.",
    accentColor: "#f08b38", emblem: "忍",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b17-phjcWCkRuIhu.png",
    sourceUrl: "https://anilist.co/character/17",
  },
  {
    id: "mikasa",
    characterName: "Mikasa Ackerman",
    seriesName: "Attack on Titan",
    shortQuote: "This world is merciless, and it is also very beautiful.",
    line: "This world can take everything from you without warning. It can show you cruelty and loss when you least expect it. But that does not mean there is nothing worth protecting. The people we love, the moments we share, and the small pieces of happiness we find are precious precisely because they can disappear. That is why I will keep fighting for them.",
    accentColor: "#a94b4b", emblem: "翼",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b40881-F3gr1PkreDvj.png",
    sourceUrl: "https://anilist.co/character/40881",
  },
  {
    id: "eren",
    characterName: "Eren Yeager",
    seriesName: "Attack on Titan",
    shortQuote: "I keep moving forward.",
    line: "Freedom has always been somewhere beyond the walls. Every time something tried to take that freedom away, I felt the need to move forward even more strongly. The road ahead may be filled with consequences, but standing still will never change anything. As long as there is something between me and the future I seek, I will continue moving forward.",
    accentColor: "#8eaa6f", emblem: "自",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg",
    sourceUrl: "https://anilist.co/character/40882",
  },
  {
    id: "thorfinn",
    characterName: "Thorfinn",
    seriesName: "Vinland Saga",
    shortQuote: "I have no enemies.",
    line: "For a long time, I believed strength meant defeating everyone who stood against me. I let anger become the reason I kept moving. But revenge only creates another person who needs revenge. Eventually you realize that continuing the same cycle does not make you free. I don't want to live by hatred anymore. I want to build something better than the world I inherited.",
    accentColor: "#7daac5", emblem: "海",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b10138-zOPrka0ddZOR.png",
    sourceUrl: "https://anilist.co/character/10138",
  },
  {
    id: "guts",
    characterName: "Guts",
    seriesName: "Berserk",
    shortQuote: "If you struggle, you survive.",
    line: "The world has never been gentle with me. Every time I thought I had found something worth protecting, fate tried to tear it away. But I am still here. I don't need the world to become kind. I only need enough strength to keep standing when it tries to break me. If there is still a road ahead, then I'll walk it.",
    accentColor: "#8e8178", emblem: "剣",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b422-XTaiTuvRohsV.png",
    sourceUrl: "https://anilist.co/character/422",
  },
  {
    id: "yami",
    characterName: "Yami Sukehiro",
    seriesName: "Black Clover",
    shortQuote: "Surpass your limits. Right here. Right now.",
    line: "There will always be someone stronger than you. There will always be a wall that looks impossible to break. But that doesn't mean you stop. When you reach your limit, that's when you find out what you're really capable of. Don't wait for the perfect moment. Don't wait until you're ready. Break through the limit standing in front of you.",
    accentColor: "#706c87", emblem: "闇",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b124440-Lpdo6y8cljV6.png",
    sourceUrl: "https://anilist.co/character/124440",
  },
  {
    id: "mikey",
    characterName: "Manjiro Sano",
    seriesName: "Tokyo Revengers",
    shortQuote: "I don't care how strong you are.",
    line: "Strength isn't only about being able to defeat someone. Sometimes strength means standing in front of the people you care about when everything is falling apart. I've made mistakes, lost people, and watched things change around me. But I refuse to let the people I care about disappear without a fight.",
    accentColor: "#d8b14f", emblem: "M",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b145341-CuPldCLZMvvf.png",
    sourceUrl: "https://anilist.co/character/145341",
  },
  {
    id: "tanjiro",
    characterName: "Tanjiro Kamado",
    seriesName: "Demon Slayer",
    shortQuote: "I can do it. I can fight.",
    line: "Being afraid doesn't mean you are weak. There will be moments when your body wants to give up and your heart tells you that you cannot continue. But someone you love may be depending on you. So take another breath, stand back up, and keep going. Even if your strength is small, you can still use it to protect someone.",
    accentColor: "#4fa9e8", emblem: "水",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png",
    sourceUrl: "https://anilist.co/character/126071",
  },
  {
    id: "hachiman",
    characterName: "Hachiman Hikigaya",
    seriesName: "Oregairu",
    shortQuote: "People don't change. They just reveal who they really are.",
    line: "People like to believe that relationships are built on honesty, but most of the time they are built on convenient misunderstandings. Everyone wants to be understood, yet nobody wants to reveal everything about themselves. Sometimes the easiest way to survive is to stop expecting people to be genuine. But perhaps the real problem is not that people cannot understand each other. Perhaps it is that understanding someone completely can be more painful than remaining strangers.",
    accentColor: "#71889b", emblem: "比",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b67065-Dhec6tE2yWA9.png",
    sourceUrl: "https://anilist.co/character/67065",
  },
  {
    id: "rocks",
    characterName: "Rocks D. Xebec",
    seriesName: "One Piece",
    shortQuote: "The world belongs to those who seize it.",
    line: "The world does not simply hand power to those who deserve it. Those who want to stand at the top must be willing to challenge everything that stands above them. The strongest ambitions are not born from acceptance. They are born from the desire to overturn the world itself and carve your own name into history.",
    accentColor: "#9e2f3f", emblem: "R",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b146411-1cWXsUjauDEU.png",
    sourceUrl: "https://anilist.co/character/146411",
  },
  {
    id: "shu",
    characterName: "Shu Kurenai",
    seriesName: "Beyblade Burst",
    shortQuote: "A true blader never gives up.",
    line: "Winning isn't simply about having the strongest Bey. Every battle reveals something about you. Your mistakes, your weaknesses, your fear, and your determination all become part of the next battle. A blader who refuses to give up can always find another way forward. The moment you stop believing in yourself is the moment the battle is truly over.",
    accentColor: "#d94d58", emblem: "S",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b134177-MzIO2Eo47flJ.jpg",
    sourceUrl: "https://anilist.co/character/134177",
  },
  {
    id: "sanji",
    characterName: "Sanji",
    seriesName: "One Piece",
    shortQuote: "A cook's hands are meant to feed people, not hurt them.",
    line: "A chef's responsibility is to feed people, no matter who they are. Hunger doesn't care about someone's past, their status, or their enemies. That's why I won't waste the hands I've dedicated to cooking. But that doesn't mean I'll stand by when someone threatens the people I care about. I'll protect my crew, even if it means putting myself between them and danger.",
    accentColor: "#e3b94f", emblem: "厨",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b305-6lisPmHtCnLT.png",
    sourceUrl: "https://anilist.co/character/305",
  },
];
