// Generate the initial public profile from the portfolio's canonical content.
// This writes locally only; it never overwrites the Google document.
import { mkdirSync, writeFileSync } from "node:fs";
import { education, certifications, projects, roles, siteConfig, techGroups } from "../lib/content";

const sections = [
  "RAJESH R — PORTFOLIO KNOWLEDGE\nProfile prepared: 16 September 2026\n",
  `IDENTITY AND SUMMARY\nName: Rajesh R (Rajesh Ravi).\nRole: Full-stack developer and AI engineer.\nLocation: Tamil Nadu, India.\nRajesh builds products across interfaces, APIs, AI pipelines, automated testing, and cloud deployment, with hands-on production healthcare experience. He focuses on clear user workflows, maintainable backend systems, useful AI integrations, and end-to-end product delivery.\nCurrent employer: Mittai Healthcare Private Limited.\nCurrent role: Junior Full Stack Developer, since July 2025.\nCurrent product: CareScribe (${siteConfig.carescribe}).\nAvailability: ${siteConfig.availability}.\nHe is interested in full-stack, AI application, platform, and healthcare engineering opportunities.`,
  `CONTACT AND PUBLIC PROFILES\nEmail: ${siteConfig.email}\nGitHub: ${siteConfig.github}\nLinkedIn: ${siteConfig.linkedin}\nPortfolio: https://rajeshportfolio-olive.vercel.app\nFor opportunities, collaborations, or project discussions, email Rajesh or use the portfolio contact section.`,
  "PROFESSIONAL EXPERIENCE\n" + roles.map((role) => `${role.title}\nCompany: ${role.company}\nDates: ${role.period}\nLocation: ${role.location}\n${role.description}\nTechnologies: ${role.stack.join(", ")}`).join("\n\n"),
  "CARESCRIBE — ADDITIONAL ENGINEERING EXPERIENCE\nRajesh's GitHub profile describes work across three React and NestJS applications, covering clinical documentation, OPD/IPD workflows, AI-assisted responses, audio and real-time flows, dashboards, billing, authentication, and administration.\nHe works with retrieval-augmented generation (RAG), Qdrant, Gemini, embeddings, prompt/context engineering, and structured AI responses.\nHe contributes to Playwright regression architecture, Vitest, Pytest, API contracts, and regression suites.\nHis cloud and release work includes Docker, Cloud Build, Kubernetes, CI/CD, health checks, and rollback safeguards.\nHe is interested in secure architecture, API hardening, authorization boundaries, DevSecOps, and OWASP-aligned testing.",
  "EDUCATION\n" + education.map((item) => `${item.title}\nInstitution: ${item.institution}\nDates: ${item.period}\nResult: ${item.score}`).join("\n\n"),
  "CERTIFICATIONS\n" + certifications.map((item) => `${item.title} (${item.year}): ${item.detail}.`).join("\n"),
  "FEATURED PROJECTS\n" + projects.map((project) => `${project.title} — ${project.type}\n${project.description}\nFeatures: ${project.features.join("; ")}.\nTechnologies: ${project.stack.join(", ")}.${project.github ? `\nRepository: ${project.github}` : ""}${project.demo ? `\nDemo: ${project.demo}` : ""}${project.downloads ? `\nDownloads: ${project.downloads.map((download) => `${download.label}: ${download.href}`).join("\n")}` : ""}`).join("\n\n"),
  "OTHER PROJECTS DESCRIBED IN THE GITHUB PROFILE\nClinical AI Platform: a private HIMS and clinical-agent architecture project separating clinical workflows from isolated AI workloads, with explicit service/data ownership, least-privileged access, auditable proposals, and human review. Listed technologies: NestJS, FastAPI, React, PostgreSQL, Prisma, Qdrant, FHIR, and RBAC. No public demo or repository is listed.\nAuthorized Security Testing Platform: a private web/API assessment project for explicitly authorized targets, with scope enforcement, async scanning, crawling, security plugins, evidence, reports, retesting, static analysis, and regression labs. Listed technologies: FastAPI, React, SQLAlchemy, PostgreSQL, HTTPX, Playwright, Docker, and OWASP WSTG. No public demo or repository is listed.\nEarlier academic and personal explorations include blockchain/Web3 and IoT prototypes. Public repository links for these earlier projects are not supplied.",
  "TECHNOLOGIES LISTED IN THE PORTFOLIO\n" + techGroups.map((group) => `${group.name}: ${group.items.join(", ")}.`).join("\n") + "\nAdditional technologies in the GitHub profile: Vitest, Pytest, GitHub Actions, LlamaIndex, HTTPX, JWT/RBAC, Prisma, FHIR, and Supabase.\nThese are listed technologies, not claims of equal expertise or a specific number of years with each tool.",
  "WORKING APPROACH\nProduct clarity: Rajesh turns unclear requirements into focused, understandable workflows.\nFull-stack ownership: he works from interface details through APIs, data models, real-time systems, and deployment.\nUseful AI: he applies AI where it improves a practical workflow.\nQuality and security: he values regression testing, explicit authorization boundaries, health verification, and maintainable delivery processes.",
  "COMMON QUESTIONS\nWho is Rajesh? Rajesh R is a full-stack developer and AI engineer from Tamil Nadu, India, building healthcare and AI-powered products.\nWhere does he work? Mittai Healthcare Private Limited, where he works on CareScribe.\nWhat is his education? BE in Information Technology from Annamalai University, 2021–2025, with an OGPA of 8.73.\nWhat are some of his projects? Resume Studio, Rajify, Rajesh OS, Job Apply Pilot, StockScope, Browser Lab, and ZoroShop.\nDoes he build AI applications? Yes. His listed work includes RAG, document-grounded agents, AI-assisted healthcare workflows, resume writing, and a shopping assistant.\nDoes he work beyond frontend? Yes. His work includes backend services, databases, AI, automation, testing, cloud deployment, and security-related engineering.\nHow can someone contact him? Email ravirajesh988@gmail.com or use the LinkedIn and portfolio links above.\nIs he open to opportunities? His portfolio states he is available for new opportunities.\nWhat is his salary or notice period? Those details have not been provided. Contact Rajesh directly.\nWhat is his exact availability or preferred work arrangement? Those details have not been provided. Contact Rajesh directly.",
  "FACT BOUNDARIES\nThe profile does not specify salary, notice period, date of birth, home address, relocation preferences, language fluency, work authorization, references, client counts, revenue, awards, or quantified business improvements.\nProject descriptions do not establish current uptime, adoption, certifications, or independent validation.\nDo not treat private architecture projects as deployed commercial products.\nEmployment dates and availability reflect the portfolio/profile content used when this document was prepared and should be updated when they change.",
];

mkdirSync("docs", { recursive: true });
writeFileSync("docs/rajesh-chat-knowledge.txt", sections.join("\n\n") + "\n", "utf8");
console.log("Prepared docs/rajesh-chat-knowledge.txt");
